const skillsList = [
  // Programming Languages
  'JavaScript',
  'TypeScript',
  'Python',
  'Java',
  'C',
  'C++',
  'C#',
  'PHP',
  'Ruby',
  'Go',
  'Swift',
  'Kotlin',
  'R',
  'MATLAB',

  // Frontend
  'React',
  'Angular',
  'Vue.js',
  'Next.js',
  'HTML',
  'CSS',
  'Sass',
  'Tailwind CSS',
  'Bootstrap',
  'jQuery',
  'Redux',
  'Webpack',

  // Backend
  'Node.js',
  'Express.js',
  'Django',
  'Flask',
  'FastAPI',
  'Laravel',
  'Spring Boot',
  'ASP.NET',
  'REST API',
  'GraphQL',

  // Databases
  'SQL',
  'MySQL',
  'PostgreSQL',
  'MongoDB',
  'Redis',
  'SQLite',
  'Oracle',
  'Firebase',

  // DevOps & Cloud
  'Git',
  'GitHub',
  'Docker',
  'Kubernetes',
  'AWS',
  'Azure',
  'GCP',
  'Linux',
  'CI/CD',
  'Jenkins',

  // Data & Analytics
  'Data Analysis',
  'Machine Learning',
  'Deep Learning',
  'TensorFlow',
  'PyTorch',
  'Pandas',
  'NumPy',
  'Power BI',
  'Tableau',
  'Excel',
  'Data Visualization',

  // Design
  'Figma',
  'Adobe XD',
  'UI/UX Design',
  'Photoshop',
  'Illustrator',

  // Finance & Accounting
  'Accounting',
  'Financial Analysis',
  'Auditing',
  'Tax Preparation',
  'Budgeting',
  'Financial Reporting',
  'Risk Management',
  'IFRS',
  'GAAP',
  'QuickBooks',
  'SAP',
  'Credit Analysis',
  'Investment Analysis',
  'Financial Modeling',
  'Compliance',

  // Education
  'Curriculum Development',
  'Lesson Planning',
  'Classroom Management',
  'Academic Assessment',
  'E-learning',
  'Research',
  'Academic Writing',
  'Student Management',
  'Educational Technology',

  // Healthcare Administration
  'Health Records Management',
  'Medical Coding',
  'ICD-10',
  'HIPAA Compliance',
  'EMR Systems',
  'Hospital Administration',
  'Healthcare IT',
  'Patient Management',
  'Medical Billing',

  // Engineering
  'AutoCAD',
  'SolidWorks',
  'Project Management',
  'Quality Control',
  'Circuit Design',
  'PLC Programming',
  'Structural Analysis',
  'CAD Design',
  'Technical Drawing',

  // Soft Skills
  'Communication',
  'Teamwork',
  'Leadership',
  'Problem Solving',
  'Critical Thinking',
  'Time Management',
  'Adaptability',
  'Creativity',
  'Attention to Detail',
  'Customer Service',
  'Negotiation',
  'Presentation Skills',
  'Public Speaking',
  'Report Writing',
  'Microsoft Office',
  'Research Skills',

  // General
  'Agile',
  'Scrum',
  'Cybersecurity',
  'Network Administration',
  'Technical Support',
  'Business Analysis',
  'Digital Marketing',
];

export default skillsList;
